### ISSUE TITLE
Can you tell me how to make a DIET model?

### ISSUE THREAD

**Issue by karrdy89** [RasaHQ/DIET-paper#4]
Hi.
I am a student studying natural language processing.
I am trying to implement the awesome  DIET model. but i need refer to the code because it is difficult.
Can you tell me the python files associated with creating and training the DIET model? or is there a separate DIET model with no dependencies? it will be of great help.
Have a nice day

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
What exactly are you interested in doing? The easiest thing to do with DIET is to use the file structure that Rasa uses to train it. From here you can still load it into the Jupyter notebook but DIET is mainly designed as a tool for Rasa. Note that DIET on it's own isn't *that* useful. It also depends on featurizers in the pipeline.  

We only offer mild compatibility with, for example, scikit-learn via [this project](https://rasahq.github.io/rasa-nlu-examples/docs/jupyter/tools/).

**Comment by karrdy89** [comment]
Thanks for your answer. I'm just practicing to implement the paper to improve my skills. I would like to see the model part, but I am struggling with the complicated structure of RASA. so I left a message asking if I could get help.

**Comment by koaning** [comment]
The code in the repository has evolved since the paper was written. It wouldn't surprise me if many parts have changed so much that the original diagram no longer holds true. With that in mind, I'm not sure if this is something useful to explore as part of a "learning more about NLU"-journey. 

It would take a lot of effort even for me (somebody who works for Rasa) to take DIET out of the library in a way that's not tightly integrated with Rasa. It's not designed to be trained/used outside of Rasa so be careful with the amount of time you're willing to spend here. 

If you're interested, an alternative might be to explore different language models/backends via the [whatlies library](https://rasahq.github.io/whatlies/). If nothing else, it's a nice playground to explore and many Non-English languages are supported there as well.

**Comment by karrdy89** [comment]
Thank you for your kind answer. I was looking too far away. so i'll start with the whatlies library and  joint bert model.
